#!/bin/bash -l

PROJECT_DIR=$HOME/Codes/graph-consensus-clustering
DATA_DIR=$PROJECT_DIR/test/data/

export OMP_NUM_THREADS=48
export OMP_PLACES=cores

BIN=$PROJECT_DIR/v8-cpp

GRAPH_FILE=$DATA_DIR/LFR/n200/LFR_n200_mu01_gamma30_beta11.mtx
INPUT_CLUSTERING_PREFIX=$DATA_DIR/LFR/n200/LFR_n200_mu01_gamma30_beta11.
NUMBER_OF_INPUT_CLUSTERING=37
$BIN $GRAPH_FILE $INPUT_CLUSTERING_PREFIX $NUMBER_OF_INPUT_CLUSTERING
